import React from "react";

export default function PrivacyPolicyPage() {
  return (
    <div className="policy-main-container">
      <h1 className="policy-title">Privacy Policy</h1>
      <div className="policy-date">Last updated: November 12, 2025</div>

      <div className="policy-section">
        <div className="section-number">1</div>
        <div className="section-content">
          <h2>Introduction</h2>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.<br />
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.
          </p>
        </div>
      </div>

      <div className="policy-section">
        <div className="section-number">2</div>
        <div className="section-content">
          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Infinitas Advisory FZCO, UAE.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: United Arab Emirates</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company...</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to Infinitas Advisory, accessible from <a href="https://infinitasadvisory.com/" target="_blank">https://infinitasadvisory.com/</a></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </div>
      </div>

      <div className="policy-section">
        <div className="section-number">3</div>
        <div className="section-content">
          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>
          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service...</p>
          <p>Usage Data may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p>When You access the Service by or through a mobile device, We may collect certain information automatically...</p>
          <h4>Tracking Technologies and Cookies</h4>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Service...</p>
          <ul>
            <li><strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device...</li>
            <li><strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files...</li>
          </ul>
          <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser...</p>
          <ul>
            <li>
              <strong>Necessary / Essential Cookies</strong><br />
              Type: Session Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies are essential...
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies identify if users have accepted the use of cookies...
            </li>
            <li>
              <strong>Functionality Cookies</strong><br />
              Type: Persistent Cookies<br />
              Administered by: Us<br />
              Purpose: These Cookies allow us to remember choices You make...
            </li>
          </ul>
          <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
        </div>
      </div>

      <div className="policy-section">
        <div className="section-number">4</div>
        <div className="section-content">
          <h2>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service...</li>
            <li><strong>For the performance of a contract</strong>: ...</li>
            <li><strong>To contact You</strong>: ...</li>
            <li><strong>To provide You</strong> with news, offers, and general info about goods, services and events...</li>
            <li><strong>To manage Your requests</strong>: ...</li>
            <li><strong>For business transfers</strong>: ...</li>
            <li><strong>For other purposes</strong>: ...</li>
          </ul>
          <p>We may share Your personal information in the following situations:</p>
          <ul>
            <li><strong>With Service Providers</strong>: We may share Your personal information with Service Providers...</li>
            <li><strong>For business transfers</strong>: ...</li>
            <li><strong>With Affiliates</strong>: ...</li>
            <li><strong>With business partners</strong>: ...</li>
            <li><strong>With other users</strong>: ...</li>
            <li><strong>With Your consent</strong>: ...</li>
          </ul>
        </div>
      </div>

      <div className="policy-section">
        <div className="section-number">5</div>
        <div className="section-content">
          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: <a href="mailto:info@infinitasadvisory.com"> info@infinitasadvisory.com </a></li>
            <li>By visiting this page on our website: <a href="https://infinitasadvisory.com/Contact" target="_blank">https://infinitasadvisory.com</a></li>
          </ul>
        </div>
      </div>
    </div>
  );
}
