/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapi5SitemapPlugin from "strapi-5-sitemap-plugin/strapi-admin";
import strapiGoogleAnalyticsDashboard from "strapi-google-analytics-dashboard/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "users-permissions": usersPermissions,
    "strapi-5-sitemap-plugin": strapi5SitemapPlugin,
    "strapi-google-analytics-dashboard": strapiGoogleAnalyticsDashboard,
  },
});
